#!/usr/bin/env python3
"""Run HotSpot 7.0 itself on our design point, with the power inputs the published studies use.

HotSpot is the solver under Stratum (MICRO'25), Helios, Tasa (ICCAD'25) and ATLAS, one of
VOXEL's two backends, and the engine CoMeT wraps. sota_comparators.py reproduces those studies'
power inputs on our own verified solver; this script asks whether the tool itself gives the
same answers on the shipping V-Cache stack (hb_stack_check.vcache_stack('F2B')).

Two HotSpot configurations:
  as-used   one lcf layer per physical layer, and HotSpot's built-in capacitance factor
            C_FACTOR = 0.333 (temperature.h, 'fitting factor to match floworks (due to
            lumping)') left in place -- the tool as a study would run it
  resolved  layers split into sublayers and the specific heat divided by 0.333, so the RC
            network is the physical one -- the check that HotSpot and our solver agree once
            they are given the same physics

Boundary. The spreader and sink are made thin, extremely conductive heat reservoirs with a
negligible convection resistance, so the TIM's top face sits at ambient as in
thermal_stack_solver; the board side of the lcf stack is adiabatic, as in ours. One block per
layer over the full die: laterally uniform, so a 2x2 grid is exact.

Scale. HotSpot prints temperatures to 0.01 K and its RK4 holds 0.01 K per step, so the tier
power is scaled until the burst-power steady rise is ~1000 K. Conduction is linear; every
result is a ratio to that rise.

HotSpot is not vendored. Build it and point HOTSPOT at the binary:
  git clone https://github.com/uvahotspot/HotSpot && make -C HotSpot    (default SUPERLU=0)
  HOTSPOT=/path/to/HotSpot/hotspot MODE=resolved WINDOWS=7e-6,1e-3 python3 scripts/hotspot_rerun.py
  HOTSPOT=... MODE=as-used WINDOWS=7e-6,200e-6,1e-3,10e-3 python3 scripts/hotspot_rerun.py
Explicit RK4 on the thin, stiff layers costs ~1.3 (as-used) to ~3.5 (resolved) s per simulated
ms, so each 24-period run takes minutes.
With SUPERLU=0 the transient is adaptive RK4 inside each ptrace row, i.e. each row's mean power
integrated accurately -- the 'trace-dt' comparator of sota_comparators.py.
"""
import os, sys, math, json, shutil, subprocess, tempfile, time
import numpy as np
sys.path.insert(0, os.path.dirname(__file__))
import thermal_stack_solver as TS
import ectc_thermal_model as M
import hb_stack_check as HB
import sota_comparators as S

C_FACTOR = 0.333                     # HotSpot temperature.h
AMBIENT = 318.15
WIDTH = math.sqrt(TS.DIE_AREA_M2)    # square die, 800 mm2
PKG = {  # spreader and sink reduced to an isothermal reservoir at ambient
    'model_type': 'grid', 'grid_rows': 2, 'grid_cols': 2, 'detailed_3D': 'off',
    'model_secondary': 0, 'leakage_used': 0, 'dtm_used': 0, 'package_model_used': 0,
    's_spreader': 1.2*WIDTH, 't_spreader': 1e-6, 'k_spreader': 1e7, 'p_spreader': 1e14,
    's_sink': 1.5*WIDTH, 't_sink': 1e-6, 'k_sink': 1e7, 'p_sink': 1e14,
    'r_convec': 1e-9, 'c_convec': 1e6, 'ambient': AMBIENT, 'init_temp': AMBIENT,
}

def lcf_layers(layers, resolved, refine=1.0):
    """Our layer list (sink first) -> HotSpot layers, far side first. Returns
    [(name, thickness, k, volumetric heat capacity as HotSpot will see it, is_tier)]."""
    out = []
    for name, t in reversed(layers):
        k, rho, cp = TS.MAT[name]
        n = 1
        if resolved:
            dz_max = (10e-6 if k >= 50 else (5e-6 if name == 'TIM' else 2e-6))/refine
            n = max(1, int(math.ceil(t/dz_max - 1e-9)))
        sp = rho*cp/(C_FACTOR if resolved else 1.0)
        out += [(name, t/n, k, sp, name == 'SRAM_tier')]*n
    return out

def replica(hl):
    """HotSpot's own 1D network for these lcf layers, solved exactly. From temperature_grid.c:
    node n carries C_FACTOR x layer n's heat capacity and joins node n+1 through layer n's FULL
    thickness (find_res: res = layers[n1].rz), so each capacitance sits at its layer's far face;
    the last layer's near face meets the reservoir package at ambient; node 0 is adiabatic."""
    n = len(hl)
    C = np.array([C_FACTOR*sp*t for _, t, k, sp, _ in hl])
    g = np.array([k/t for _, t, k, sp, _ in hl])
    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] += g[i]
        if i + 1 < n:
            A[i, i+1] -= g[i]; A[i+1, i] -= g[i]; A[i+1, i+1] += g[i]
    return S.Modal.network(A, C, [i for i, h in enumerate(hl) if h[4]], TS.DIE_AREA_M2)

def write_case(d, hl):
    lcf = ['# generated by scripts/hotspot_rerun.py']
    for i, (name, t, k, sp, tier) in enumerate(hl):
        blk = 'tier' if tier else f'b{i}'
        open(os.path.join(d, f'L{i}.flp'), 'w').write(f'{blk}\t{WIDTH:.9e}\t{WIDTH:.9e}\t0\t0\n')
        lcf += [f'# {name}', str(i), 'Y', 'Y' if tier else 'N', f'{sp:.9e}', f'{1.0/k:.9e}',
                f'{t:.9e}', f'L{i}.flp', '']
    open(os.path.join(d, 'stack.lcf'), 'w').write('\n'.join(lcf))
    if sum(1 for h in hl if h[4]) != 1:
        raise SystemExit('expected exactly one tier layer (split tiers would need one column each)')

def run_hotspot(hs, d, ptrace_rows, dt, tag, init=None, transient=False):
    open(os.path.join(d, f'{tag}.ptrace'), 'w').write(
        'tier\n' + ''.join(f'{p:.9e}\n' for p in ptrace_rows))
    cmd = [hs, '-c', os.path.join(d, 'hs.config'), '-p', f'{tag}.ptrace', '-grid_layer_file',
           'stack.lcf', '-sampling_intvl', f'{dt:.9e}']
    for k_, v in PKG.items(): cmd += [f'-{k_}', str(v)]
    if init: cmd += ['-init_file', init]
    cmd += ['-o', f'{tag}.ttrace'] if transient else ['-steady_file', f'{tag}.steady']
    t0 = time.time()
    r = subprocess.run(cmd, cwd=d, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f'HotSpot failed ({tag}):\n{r.stdout[-2000:]}\n{r.stderr[-2000:]}')
    return time.time() - t0

def steady_tier(d, tag):
    for line in open(os.path.join(d, f'{tag}.steady')):
        name, val = line.split()
        if name.endswith('_tier'): return float(val)
    raise SystemExit('no tier block in the steady file')

def transient_tier(d, tag):
    rows = open(os.path.join(d, f'{tag}.ttrace')).read().split('\n')
    col = rows[0].split().index('tier')
    return np.array([float(r.split()[col]) for r in rows[1:] if r.strip()])

def window_rows(P, window, n):
    return [P*S.burst_overlap(m*window, window)/window for m in range(n)]

def base_config(d, hs):
    """HotSpot's own 3D example config (example4) as the base; PKG overrides it."""
    src = os.path.join(os.path.dirname(hs), 'examples', 'example4', 'example.config')
    if not os.path.exists(src):
        raise SystemExit(f'cannot find {src}; HOTSPOT must point into a HotSpot checkout')
    open(os.path.join(d, 'hs.config'), 'w').write(open(src).read())

def rerun(hs, layers, resolved, windows, periods, log):
    d = tempfile.mkdtemp(prefix='hotspot_rerun_')
    base_config(d, hs)
    hl = lcf_layers(layers, resolved)
    write_case(d, hl)
    R = S.Modal(layers, TS.DIE_AREA_M2).R
    P = 1000.0/R                                       # ~1000 K burst-power steady rise
    res = {'n_lcf_layers': len(hl)}
    sec = run_hotspot(hs, d, [P], 1e-3, 'peak')
    dT_peak = steady_tier(d, 'peak') - AMBIENT
    res['R_hotspot_K_per_W'] = dT_peak/P
    n_avg = int(round(PERIOD_US/7))                    # one period of 7 us rows
    run_hotspot(hs, d, window_rows(P, 7e-6, n_avg), 7e-6, 'avg')
    res['static-avg'] = (steady_tier(d, 'avg') - AMBIENT)/dT_peak
    log(f"  {'resolved' if resolved else 'as-used'}: {len(hl)} lcf layers, "
        f"R {res['R_hotspot_K_per_W']:.5f} K/W (ours {R:.5f}), static-avg {res['static-avg']:.5f} "
        f"(duty {TS.DUTY:.4f})  [{sec:.1f} s]")
    for w in windows:
        n = int(math.ceil(max(periods*TS.PERIOD, 20*w)/w))    # >= 20 rows for coarse windows
        sec = run_hotspot(hs, d, window_rows(P, w, n), w, f'w{w*1e6:.0f}', init='avg.steady',
                          transient=True)
        T = transient_tier(d, f'w{w*1e6:.0f}') - AMBIENT
        tail = T[int(len(T)*0.75):]                    # last quarter: settled, phases sampled
        res[S.wkey('trace', w)] = tail.max()/dT_peak
        res[S.wkey('replica', w)] = same_protocol(hl, w, n)
        log(f'    {w*1e6:>8.0f} us rows x {n:>6}: peak fraction {tail.max()/dT_peak:.5f}, '
            f'replica {res[S.wkey("replica", w)]:.5f}  [{sec:.1f} s]')
    if not os.environ.get('KEEP'):
        shutil.rmtree(d)                               # KEEP=1 leaves the HotSpot run folder
    return res

def same_protocol(hl, w, n):
    """The replica network driven exactly as the HotSpot run was: n rows of window w from the
    average-power steady state, maximum over the last quarter. Which burst/row alignments a
    run happens to contain moves a coarse-row peak by a few tenths of a percent, so the tool
    is compared with its replica on identical rows, not with a long-run maximum."""
    rep = replica(hl)
    T = rep.trace_series(w, n, rep.w/rep.lam*TS.DUTY)
    return T[int(n*0.75):].max()/rep.R

PERIOD_US = TS.PERIOD*1e6

if __name__ == '__main__':
    # MODE picks one configuration so the two can run side by side; each writes its own file.
    # MODE=replica needs no HotSpot binary.
    mode = os.environ.get('MODE', 'resolved')
    hs = os.environ.get('HOTSPOT')
    if mode != 'replica' and (not hs or not os.path.exists(hs)):
        sys.exit('set HOTSPOT to a built HotSpot binary (see the module docstring)')
    HB.use_device(HB.SI)
    layers = HB.vcache_stack('F2B')
    ours = S.comparators(layers, HB.SI)
    if mode == 'replica':
        # HotSpot's network rebuilt in Python and solved exactly: does it reproduce the tool,
        # and does refining its layers converge to our answer?
        rows = {}
        print(f"{'network':>34} {'layers':>6} {'burst (exact)':>14} {'1 ms rows':>10} {'10 ms rows':>11}")
        cases = [('as-used (1 node/layer, C x0.333)', False, 1.0)]
        cases += [(f'resolved, sublayers /{r:g}', True, r) for r in (1.0, 2.0, 4.0, 8.0, 16.0)]
        for label, resolved, r in cases:
            hl = lcf_layers(layers, resolved, r); rep = replica(hl)
            v = {'layers': len(hl), 'exact': rep.square_pss(),
                 'trace-7us': rep.trace_peak(7e-6), 'trace-200us': rep.trace_peak(200e-6),
                 'trace-1000us': rep.trace_peak(1e-3), 'trace-10000us': rep.trace_peak(10e-3)}
            rows[label] = v
            print(f"{label:>34} {len(hl):>6} {v['exact']:>8.4f} ({M.bw_cap_TBs(20, 0.5, v['exact']):.1f}) "
                  f"{v['trace-1000us']:>10.4f} {v['trace-10000us']:>11.4f}")
        print(f"{'ours (cell-centred, 0.5 um)':>34} {'':>6} {ours['exact']:>8.4f} "
              f"({M.bw_cap_TBs(20, 0.5, ours['exact']):.1f}) {ours['trace-1000us']:>10.4f} "
              f"{ours['trace-10000us']:>11.4f}")
        dst = os.path.join(os.path.dirname(__file__), '..', 'assets', 'sweep', 'hotspot_replica.json')
        json.dump({'stack': 'V-Cache dims, F2B (6 um)', 'replica': rows, 'ours': ours}, open(dst, 'w'), indent=1)
        print(f'\nwrote {os.path.relpath(dst)}')
        sys.exit(0)
    commit = subprocess.run(['git', '-C', os.path.dirname(hs), 'rev-parse', 'HEAD'],
                            capture_output=True, text=True).stdout.strip()
    windows = [float(x) for x in os.environ.get('WINDOWS', '7e-6,1e-3').split(',')]
    periods = float(os.environ.get('PERIODS', '24'))
    print(f'HotSpot {commit[:7]} ({mode}) on the V-Cache F2B stack; windows {windows}, '
          f'{periods:g} periods per run')
    res = rerun(hs, layers, mode == 'resolved', windows, periods, print)
    print(f"\n{'input':>14} {'ours':>16} {'HotSpot ' + mode:>18}")
    for key in ['static-avg'] + [S.wkey('trace', w) for w in windows]:
        ref = ours.get(key, ours['exact'])          # 7 us rows resolve the burst: compare to exact
        print(f"{key:>14} {ref:>.4f} ({M.bw_cap_TBs(20, 0.5, ref):>5.1f} TB/s) "
              f"{res[key]:>.4f} ({M.bw_cap_TBs(20, 0.5, res[key]):>5.1f} TB/s) {(res[key]/ref - 1)*100:+6.2f}%")
    dst = os.path.join(os.path.dirname(__file__), '..', 'assets', 'sweep', f'hotspot_rerun_{mode}.json')
    json.dump({'hotspot_commit': commit, 'mode': mode, 'stack': 'V-Cache dims, F2B (6 um)',
               'windows_s': windows, 'periods': periods, 'hotspot': res, 'ours': ours},
              open(dst, 'w'), indent=1)
    print(f'\nwrote {os.path.relpath(dst)}')
